packaging_format = 2

id = "yellow"
name = "Yellow"
description.en = "Content management system for simple website"
description.fr = "Système de gestion de contenu pour un site simple"

version = "2026.09.11~ynh1"

maintainers = []

[upstream]
license = "GPL-2.0-only"
website = "https://datenstrom.se/yellow/"
demo = "https://datenstrom.se/yellow/demo/"
admindoc = "https://datenstrom.se/yellow/help/"
code = "https://github.com/datenstrom/yellow/"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/yellow"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/datenstrom/yellow/archive/f2c6e416cecb2a2a77030a60f8dc6af5327e98d0.tar.gz"
        sha256 = "e134c70bd1abb5057eace06b49345d84770a068ae30943b200d5f1fc5ec08e28"
        autoupdate.upstream = "https://github.com/datenstrom/yellow"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.5-mbstring, php8.5-xmlrpc, php8.5-sqlite3, php8.5-soap, php8.5-gd, php8.5-xml, php8.5-cli, php8.5-curl, php8.5-zip"
