test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.24ae37ee.name = "Upgrade from 0.8.20~ynh4"
